/*
 * mpi/codegen/lib/mpi_Dims_create/mpi_Dims_create_mex.c
 *
 * Auxiliary code for mexFunction of mpi_Dims_create
 *
 * C source code generated by m2c.
 * %#m2c options:592722e76bfeb326d5f7ae2a786346ed
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "mpi_Dims_create.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __mpi_Dims_create_api(mxArray **plhs, const mxArray ** prhs) {
    int32_T              nnodes;
    int32_T              ndims;
    emxArray_int32_T     dims;
    int32_T             *info;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mpi_Dims_create:WrongInputType",
            "Input argument nnodes has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mpi_Dims_create:WrongSizeOfInputArg",
            "Argument nnodes should be a scalar.");
    nnodes = *(int32_T*)mxGetData(prhs[0]);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mpi_Dims_create:WrongInputType",
            "Input argument ndims has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("mpi_Dims_create:WrongSizeOfInputArg",
            "Argument ndims should be a scalar.");
    ndims = *(int32_T*)mxGetData(prhs[1]);
    init_emxArray((emxArray__common*)(&dims), 1);

    info = mxMalloc(sizeof(int32_T));

    toplevel = mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    mpi_Dims_create(nnodes, ndims, &dims, info, toplevel);

    /* Deallocate input and marshall out function outputs */
    /* Nothing to be done for nnodes */
    /* Nothing to be done for ndims */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&dims), mxINT32_CLASS);
    mxFree(dims.size);
    plhs[1] = move_scalar_to_mxArray(info, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3] = {NULL, NULL, NULL};
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 2) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("mpi_Dims_create:TooManyOutputArguments",
                "Too many output arguments for entry-point mpi_Dims_create.\n");
        /* Call the API function. */
        __mpi_Dims_create_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("mpi_Dims_create:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point mpi_Dims_create.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
