/*
 * cuBlasGetEnum_mex.c
 *
 * Auxiliary code for mexFunction of cuBlasGetEnum
 *
 * C source code generated by m2c.
 * %#m2c options:f8b57e294c05fcbaad377e420790b837
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C header file generated by codegen in lib mode */
#include "cuBlasGetEnum.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __cuBlasGetEnum_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_char_T      str;
    int32_T              _val;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("cuBlasGetEnum:WrongInputType",
            "Input argument str has incorrect data type; char is expected.");
    if (mxGetNumberOfElements(prhs[0]) && mxGetDimensions(prhs[0])[0] != 1) 
        mexErrMsgIdAndTxt("cuBlasGetEnum:WrongSizeOfInputArg",
            "Dimension 1 of str should equal 1.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&str), "str", 2);

    /* Invoke the target function */
    _val = cuBlasGetEnum(&str);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&str));
    plhs[0] = copy_scalar_to_mxArray(&_val, mxINT32_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 1) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("cuBlasGetEnum:TooManyOutputArguments",
                "Too many output arguments for entry-point cuBlasGetEnum.\n");
        /* Call the API function. */
        __cuBlasGetEnum_api(plhs, prhs);
    }
    else
        mexErrMsgIdAndTxt("cuBlasGetEnum:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point cuBlasGetEnum.");
}
