/*
 * util/codegen/lib/mpi_get_sizeof/mpi_get_sizeof_mex.c
 *
 * Auxiliary code for mexFunction of mpi_get_sizeof
 *
 * C source code generated by m2c.
 * %#m2c options:51b8dc0108e27c00e7ef7a1c186f5f18
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "mpi_get_sizeof.h"
#include "mpi_get_sizeof_types.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __mpi_get_sizeof_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_char_T      typename;
    int32_T              _n;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("mpi_get_sizeof:WrongInputType",
            "Input argument typename has incorrect data type; char is expected.");
    if (mxGetNumberOfElements(prhs[0]) && mxGetDimensions(prhs[0])[0] != 1) 
        mexErrMsgIdAndTxt("mpi_get_sizeof:WrongSizeOfInputArg",
            "Dimension 1 of typename should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&typename), "typename", 2);

    /* Invoke the target function */
    _n = mpi_get_sizeof(&typename);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&typename));
    plhs[0] = copy_scalar_to_mxArray(&_n, mxINT32_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 1) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("mpi_get_sizeof:TooManyOutputArguments",
                "Too many output arguments for entry-point mpi_get_sizeof.\n");
        /* Call the API function. */
        __mpi_get_sizeof_api(plhs, prhs);
    }
    else
        mexErrMsgIdAndTxt("mpi_get_sizeof:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point mpi_get_sizeof.");
}
