/*
 * dense/solve/codegen/lib/backsolve/backsolve_mex.c
 *
 * Auxiliary code for mexFunction of backsolve
 *
 * C source code generated by m2c.
 * %#m2c options:f744a632682910693ed19630bc524771
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "backsolve.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __backsolve_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_real_T      R;
    emxArray_real_T      bs;
    int32_T              cend;
    emxArray_real_T      ws;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("backsolve:WrongInputType",
            "Input argument R has incorrect data type; double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&R), "R", 2);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("backsolve:WrongInputType",
            "Input argument bs has incorrect data type; double is expected.");
    copy_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&bs), "bs", 2);

    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("backsolve:WrongInputType",
            "Input argument cend has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("backsolve:WrongSizeOfInputArg",
            "Argument cend should be a scalar.");
    cend = *(int32_T*)mxGetData(prhs[2]);

    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("backsolve:WrongInputType",
            "Input argument ws has incorrect data type; double is expected.");
    alias_mxArray_to_emxArray(prhs[3], (emxArray__common *)(&ws), "ws", 2);

    /* Invoke the target function */
    backsolve(&R, &bs, cend, &ws);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&R));
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&bs), mxDOUBLE_CLASS);
    mxFree(bs.size);
    /* Nothing to be done for cend */
    free_emxArray((emxArray__common*)(&ws));

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 4) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("backsolve:TooManyOutputArguments",
                "Too many output arguments for entry-point backsolve.\n");
        /* Call the API function. */
        __backsolve_api(plhs, prhs);
    }
    else
        mexErrMsgIdAndTxt("backsolve:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point backsolve.");
}
