/*
 * cuVecDestroy_mex.c
 *
 * Auxiliary code for mexFunction of cuVecDestroy
 *
 * C source code generated by m2c.
 * %#m2c options:4fe9ffe9e67ed11f9e6b151c1ca557e8
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C header file generated by codegen in lib mode */
#include "cuVecDestroy.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void marshallin_struct0_T(struct0_T *pStruct, const mxArray *mx, const char *mname) {
    mxArray             *sub_mx;

    if (!mxIsStruct(mx))
        M2C_error("marshallin_struct0_T:WrongType",
            "Input argument %s has incorrect data type; struct is expected.", mname);
    if (!mxGetField(mx, 0, "data"))
        M2C_error("marshallin_struct0_T:WrongType",
            "Input argument %s is missing the field data.", mname);
    if (!mxGetField(mx, 0, "type"))
        M2C_error("marshallin_struct0_T:WrongType",
            "Input argument %s is missing the field type.", mname);
    if (!mxGetField(mx, 0, "dims"))
        M2C_error("marshallin_struct0_T:WrongType",
            "Input argument %s is missing the field dims.", mname);
    if (mxGetNumberOfFields(mx) > 3)
        M2C_warn("marshallin_struct0_T:ExtraFields",
            "Extra fields in %s and are ignored.", mname);

    sub_mx = mxGetField(mx, 0, "data");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxUINT64_CLASS)
        mexErrMsgIdAndTxt("marshallin_struct0_T:WrongInputType",
            "Input argument data has incorrect data type; uint64 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_struct0_T:WrongSizeOfInputArg",
            "Argument data should be a scalar.");
    pStruct->data = *(uint64_T*)mxGetData(sub_mx);

    sub_mx = mxGetField(mx, 0, "type");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("marshallin_struct0_T:WrongInputType",
            "Input argument type has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_struct0_T:WrongSizeOfInputArg",
            "Argument type should be a scalar.");
    pStruct->type = *(int32_T*)mxGetData(sub_mx);

    sub_mx = mxGetField(mx, 0, "dims");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("marshallin_struct0_T:WrongInputType",
            "Input argument dims has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_struct0_T:WrongSizeOfInputArg",
            "Argument dims should be a scalar.");
    pStruct->dims = *(int32_T*)mxGetData(sub_mx);
}

static mxArray *marshallout_struct0_T(struct0_T *pStruct) {
    const char           *fields[] = {"data", "type", "dims"};
    int                  one=1;
    mxArray              *mx = create_struct_mxArray(1, &one, 3, fields);

    mxSetField(mx, 0, "data", copy_scalar_to_mxArray(&pStruct->data, mxUINT64_CLASS));
    mxSetField(mx, 0, "type", copy_scalar_to_mxArray(&pStruct->type, mxINT32_CLASS));
    mxSetField(mx, 0, "dims", copy_scalar_to_mxArray(&pStruct->dims, mxINT32_CLASS));
    return mx;
}



static void __cuVecDestroy_api(mxArray **plhs, const mxArray ** prhs) {
    struct0_T            vec;
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxSTRUCT_CLASS)
        mexErrMsgIdAndTxt("cuVecDestroy:WrongInputType",
            "Input argument vec has incorrect data type; struct is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuVecDestroy:WrongSizeOfInputArg",
            "Argument vec should be a scalar.");
    marshallin_struct0_T(&vec, prhs[0], "vec");

    errCode = mxMalloc(sizeof(int32_T));

    toplevel = mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    cuVecDestroy(&vec, errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    plhs[0] = marshallout_struct0_T(&vec);
    plhs[1] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("cuVecDestroy:TooManyOutputArguments",
                "Too many output arguments for entry-point cuVecDestroy.\n");
        /* Call the API function. */
        __cuVecDestroy_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("cuVecDestroy:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point cuVecDestroy.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
