/*
 * dense/solve/codegen/lib/solve_getrs/solve_getrs_mex.c
 *
 * Auxiliary code for mexFunction of solve_getrs
 *
 * C source code generated by m2c.
 * %#m2c options:56181d047c3a2213571b93db2965914f
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "solve_getrs.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __solve_getrs_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_real_T      A;
    emxArray_real_T      b;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("solve_getrs:WrongInputType",
            "Input argument A has incorrect data type; double is expected.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&A), "A", 2);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("solve_getrs:WrongInputType",
            "Input argument b has incorrect data type; double is expected.");
    copy_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&b), "b", 2);

    /* Invoke the target function */
    solve_getrs(&A, &b);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&A));
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&b), mxDOUBLE_CLASS);
    mxFree(b.size);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 2) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("solve_getrs:TooManyOutputArguments",
                "Too many output arguments for entry-point solve_getrs.\n");
        /* Call the API function. */
        __solve_getrs_api(plhs, prhs);
    }
    else
        mexErrMsgIdAndTxt("solve_getrs:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point solve_getrs.");
}
