function [vec, errCode, toplevel] = cuVecCopySubFromGPU_async(n, cuVec, ...
    incCuVec, vec, istart, inc, strm)
[vec, errCode, toplevel] = cuVecCopySubFromGPU(n, cuVec, ...
    incCuVec, vec, istart, inc, strm);
