function lib2mex(funcname, ldflags, opflags, args)
% Generate a MEXFunction for a C library created by m2c.
% It also generates a MATLAB script 'mex_fname.m for building
% the generated file. Before calling this script, m2c should
% have been called on the function, or codegen should be present.
% The generated MEX file is not as general as that generated by m2mex,
% but it is more efficient. The generated C file and build script
% will be located in codegen/lib/funcname.
%
% The -g option will enable debugging for the mex command.
%
% See also m2c, lib2exe

lib2mex_exe(funcname, ldflags, opflags, args, false);
