/*
 * dense/solve/codegen/lib/rescale_matrix/rescale_matrix_mex.c
 *
 * Auxiliary code for mexFunction of rescale_matrix
 *
 * C source code generated by m2c.
 * %#m2c options:2aef92aa135e1490a09d44bbf27e044f
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "rescale_matrix.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __rescale_matrix_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_real_T      V;
    int32_T              ncols;
    emxArray_real_T      ts;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("rescale_matrix:WrongInputType",
            "Input argument V has incorrect data type; double is expected.");
    copy_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&V), "V", 2);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("rescale_matrix:WrongInputType",
            "Input argument ncols has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) != 1)
        mexErrMsgIdAndTxt("rescale_matrix:WrongSizeOfInputArg",
            "Argument ncols should be a scalar.");
    ncols = *(int32_T*)mxGetData(prhs[1]);

    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("rescale_matrix:WrongInputType",
            "Input argument ts has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[2]) && mxGetDimensions(prhs[2])[1] != 1) 
        mexErrMsgIdAndTxt("rescale_matrix:WrongSizeOfInputArg",
            "Dimension 2 of ts should equal 1.");
    copy_mxArray_to_emxArray(prhs[2], (emxArray__common *)(&ts), "ts", 1);

    /* Invoke the target function */
    rescale_matrix(&V, ncols, &ts);

    /* Deallocate input and marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&V), mxDOUBLE_CLASS);
    mxFree(V.size);
    /* Nothing to be done for ncols */
    plhs[1] = move_emxArray_to_mxArray((emxArray__common*)(&ts), mxDOUBLE_CLASS);
    mxFree(ts.size);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2] = {NULL, NULL};
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 3) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("rescale_matrix:TooManyOutputArguments",
                "Too many output arguments for entry-point rescale_matrix.\n");
        /* Call the API function. */
        __rescale_matrix_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("rescale_matrix:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point rescale_matrix.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
