/*
 * mpi/codegen/lib/mpi_Error_string/mpi_Error_string_mex.c
 *
 * Auxiliary code for mexFunction of mpi_Error_string
 *
 * C source code generated by m2c.
 * %#m2c options:9f24c68e15bf2f81e606c54eee363e98
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C header file generated by codegen in lib mode */
#include "mpi_Error_string.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __mpi_Error_string_api(mxArray **plhs, const mxArray ** prhs) {
    int32_T              errcode;
    emxArray_char_T      msg;
    int32_T             *info;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("mpi_Error_string:WrongInputType",
            "Input argument errcode has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("mpi_Error_string:WrongSizeOfInputArg",
            "Argument errcode should be a scalar.");
    errcode = *(int32_T*)mxGetData(prhs[0]);
    init_emxArray((emxArray__common*)(&msg), 2);

    info = mxMalloc(sizeof(int32_T));

    toplevel = mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    mpi_Error_string(errcode, &msg, info, toplevel);

    /* Deallocate input and marshall out function outputs */
    /* Nothing to be done for errcode */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&msg), mxCHAR_CLASS);
    mxFree(msg.size);
    plhs[1] = move_scalar_to_mxArray(info, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 1) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("mpi_Error_string:TooManyOutputArguments",
                "Too many output arguments for entry-point mpi_Error_string.\n");
        /* Call the API function. */
        __mpi_Error_string_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("mpi_Error_string:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point mpi_Error_string.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
