/*
 * cuDeviceSynchronize_mex.c
 *
 * Auxiliary code for mexFunction of cuDeviceSynchronize
 *
 * C source code generated by m2c.
 * %#m2c options:a86f06273668c7ee1c254c6a92bd888a
 *
 */

#ifdef MATLAB_MEX_FILE
#include "mex.h"
#else
#include "matrix.h"
#endif
/* Include the C header file generated by codegen in lib mode */
#include "cuDeviceSynchronize.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __cuDeviceSynchronize_api(mxArray **plhs, const mxArray ** prhs) {
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    errCode = mxMalloc(sizeof(int32_T));

    toplevel = mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    cuDeviceSynchronize(errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    plhs[0] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[1] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 0) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cuDeviceSynchronize:TooManyOutputArguments",
                "Too many output arguments for entry-point cuDeviceSynchronize.\n");
        /* Call the API function. */
        __cuDeviceSynchronize_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("cuDeviceSynchronize:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point cuDeviceSynchronize.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
