/*
 * mpi/codegen/lib/mpi_Get_processor_name/mpi_Get_processor_name_mex.c
 *
 * Auxiliary code for mexFunction of mpi_Get_processor_name
 *
 * C source code generated by m2c.
 * %#m2c options:a86f06273668c7ee1c254c6a92bd888a
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "mpi_Get_processor_name.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __mpi_Get_processor_name_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_char_T      name;
    int32_T             *info;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    init_emxArray((emxArray__common*)(&name), 2);

    info = (int32_T*)mxMalloc(sizeof(int32_T));

    toplevel = (boolean_T*)mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    mpi_Get_processor_name(&name, info, toplevel);

    /* Deallocate input and marshall out function outputs */
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&name), mxCHAR_CLASS);
    mxFree(name.size);
    plhs[1] = move_scalar_to_mxArray(info, mxINT32_CLASS);
    plhs[2] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[3] = {NULL, NULL, NULL};
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 0) {
        if (nlhs > 3)
            mexErrMsgIdAndTxt("mpi_Get_processor_name:TooManyOutputArguments",
                "Too many output arguments for entry-point mpi_Get_processor_name.\n");
        /* Call the API function. */
        __mpi_Get_processor_name_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("mpi_Get_processor_name:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point mpi_Get_processor_name.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
