/*
 * cuVecCopySubToGPU_mex.c
 *
 * Auxiliary code for mexFunction of cuVecCopySubToGPU
 *
 * C source code generated by m2c.
 * %#m2c options:2600c76323fbeebe646da6cc691bb015
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "cuVecCopySubToGPU.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void marshallin_struct0_T(struct0_T *pStruct, const mxArray *mx, const char *mname) {
    mxArray             *sub_mx;

    if (!mxIsStruct(mx))
        M2C_error("marshallin_const_struct0_T:WrongType",
            "Input argument %s has incorrect data type; struct is expected.", mname);
    if (!mxGetField(mx, 0, "data"))
        M2C_error("marshallin_const_struct0_T:WrongType",
            "Input argument %s is missing the field data.", mname);
    if (!mxGetField(mx, 0, "type"))
        M2C_error("marshallin_const_struct0_T:WrongType",
            "Input argument %s is missing the field type.", mname);
    if (!mxGetField(mx, 0, "dims"))
        M2C_error("marshallin_const_struct0_T:WrongType",
            "Input argument %s is missing the field dims.", mname);
    if (mxGetNumberOfFields(mx) > 3)
        M2C_warn("marshallin_const_struct0_T:ExtraFields",
            "Extra fields in %s and are ignored.", mname);

    sub_mx = mxGetField(mx, 0, "data");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxUINT64_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_struct0_T:WrongInputType",
            "Input argument data has incorrect data type; uint64 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_const_struct0_T:WrongSizeOfInputArg",
            "Argument data should be a scalar.");
    pStruct->data = *(uint64_T*)mxGetData(sub_mx);

    sub_mx = mxGetField(mx, 0, "type");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_struct0_T:WrongInputType",
            "Input argument type has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_const_struct0_T:WrongSizeOfInputArg",
            "Argument type should be a scalar.");
    pStruct->type = *(int32_T*)mxGetData(sub_mx);

    sub_mx = mxGetField(mx, 0, "dims");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_struct0_T:WrongInputType",
            "Input argument dims has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_const_struct0_T:WrongSizeOfInputArg",
            "Argument dims should be a scalar.");
    pStruct->dims = *(int32_T*)mxGetData(sub_mx);
}



static void marshallin_const_struct1_T(struct1_T *pStruct, const mxArray *mx, const char *mname) {
    mxArray             *sub_mx;

    if (!mxIsStruct(mx))
        M2C_error("marshallin_const_struct1_T:WrongType",
            "Input argument %s has incorrect data type; struct is expected.", mname);
    if (!mxGetField(mx, 0, "data"))
        M2C_error("marshallin_const_struct1_T:WrongType",
            "Input argument %s is missing the field data.", mname);
    if (!mxGetField(mx, 0, "type"))
        M2C_error("marshallin_const_struct1_T:WrongType",
            "Input argument %s is missing the field type.", mname);
    if (!mxGetField(mx, 0, "nitems"))
        M2C_error("marshallin_const_struct1_T:WrongType",
            "Input argument %s is missing the field nitems.", mname);
    if (mxGetNumberOfFields(mx) > 3)
        M2C_warn("marshallin_const_struct1_T:ExtraFields",
            "Extra fields in %s and are ignored.", mname);

    sub_mx = mxGetField(mx, 0, "data");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxUINT8_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_struct1_T:WrongInputType",
            "Input argument data has incorrect data type; uint8 is expected.");
    if (mxGetNumberOfElements(sub_mx) && mxGetDimensions(sub_mx)[1] != 1) 
        mexErrMsgIdAndTxt("marshallin_const_struct1_T:WrongSizeOfInputArg",
            "Dimension 2 of data should equal 1.");
    pStruct->data = mxMalloc(sizeof(emxArray_uint8_T));
    init_emxArray((emxArray__common*)(pStruct->data), 1);
    alias_mxArray_to_emxArray(sub_mx, (emxArray__common *)(pStruct->data), "data", 1);

    sub_mx = mxGetField(mx, 0, "type");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxCHAR_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_struct1_T:WrongInputType",
            "Input argument type has incorrect data type; char is expected.");
    if (mxGetNumberOfElements(sub_mx) && mxGetDimensions(sub_mx)[0] != 1) 
        mexErrMsgIdAndTxt("marshallin_const_struct1_T:WrongSizeOfInputArg",
            "Dimension 1 of type should equal 1.");
    pStruct->type = mxMalloc(sizeof(emxArray_char_T));
    init_emxArray((emxArray__common*)(pStruct->type), 2);
    alias_mxArray_to_emxArray(sub_mx, (emxArray__common *)(pStruct->type), "type", 2);

    sub_mx = mxGetField(mx, 0, "nitems");
    if (mxGetNumberOfElements(sub_mx) && mxGetClassID(sub_mx) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("marshallin_const_struct1_T:WrongInputType",
            "Input argument nitems has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(sub_mx) != 1)
        mexErrMsgIdAndTxt("marshallin_const_struct1_T:WrongSizeOfInputArg",
            "Argument nitems should be a scalar.");
    pStruct->nitems = *(int32_T*)mxGetData(sub_mx);
}
static void destroy_struct1_T(struct1_T *pStruct) {

    free_emxArray((emxArray__common*)(pStruct->data));
    mxFree(pStruct->data);

    free_emxArray((emxArray__common*)(pStruct->type));
    mxFree(pStruct->type);


}


static void __cuVecCopySubToGPU_api(mxArray **plhs, const mxArray ** prhs) {
    int32_T              n;
    emxArray_real_T      vec;
    int32_T              istart;
    int32_T              inc;
    struct0_T            cuVec;
    int32_T              incCuVec;
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongInputType",
            "Input argument n has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongSizeOfInputArg",
            "Argument n should be a scalar.");
    n = *(int32_T*)mxGetData(prhs[0]);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongInputType",
            "Input argument vec has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[1]) && mxGetDimensions(prhs[1])[1] != 1) 
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongSizeOfInputArg",
            "Dimension 2 of vec should equal 1.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&vec), "vec", 1);

    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongInputType",
            "Input argument istart has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongSizeOfInputArg",
            "Argument istart should be a scalar.");
    istart = *(int32_T*)mxGetData(prhs[2]);

    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongInputType",
            "Input argument inc has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongSizeOfInputArg",
            "Argument inc should be a scalar.");
    inc = *(int32_T*)mxGetData(prhs[3]);

    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxSTRUCT_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongInputType",
            "Input argument cuVec has incorrect data type; struct is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongSizeOfInputArg",
            "Argument cuVec should be a scalar.");
    marshallin_struct0_T(&cuVec, prhs[4], "cuVec");

    if (mxGetNumberOfElements(prhs[5]) && mxGetClassID(prhs[5]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongInputType",
            "Input argument incCuVec has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongSizeOfInputArg",
            "Argument incCuVec should be a scalar.");
    incCuVec = *(int32_T*)mxGetData(prhs[5]);

    errCode = mxMalloc(sizeof(int32_T));

    toplevel = mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    cuVecCopySubToGPU(n, &vec, istart, inc, &cuVec, incCuVec, errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    /* Nothing to be done for n */
    free_emxArray((emxArray__common*)(&vec));
    /* Nothing to be done for istart */
    /* Nothing to be done for inc */
    /* Nothing to be done for incCuVec */
    plhs[0] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[1] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}

static void __cuVecCopySubToGPU_async_api(mxArray **plhs, const mxArray ** prhs) {
    int32_T              n;
    emxArray_real_T      vec;
    int32_T              istart;
    int32_T              inc;
    struct0_T            cuVec;
    int32_T              incCuVec;
    struct1_T            strm;
    int32_T             *errCode;
    boolean_T           *toplevel;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument n has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Argument n should be a scalar.");
    n = *(int32_T*)mxGetData(prhs[0]);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxDOUBLE_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument vec has incorrect data type; double is expected.");
    if (mxGetNumberOfElements(prhs[1]) && mxGetDimensions(prhs[1])[1] != 1) 
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Dimension 2 of vec should equal 1.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&vec), "vec", 1);

    if (mxGetNumberOfElements(prhs[2]) && mxGetClassID(prhs[2]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument istart has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[2]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Argument istart should be a scalar.");
    istart = *(int32_T*)mxGetData(prhs[2]);

    if (mxGetNumberOfElements(prhs[3]) && mxGetClassID(prhs[3]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument inc has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[3]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Argument inc should be a scalar.");
    inc = *(int32_T*)mxGetData(prhs[3]);

    if (mxGetNumberOfElements(prhs[4]) && mxGetClassID(prhs[4]) != mxSTRUCT_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument cuVec has incorrect data type; struct is expected.");
    if (mxGetNumberOfElements(prhs[4]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Argument cuVec should be a scalar.");
    marshallin_struct0_T(&cuVec, prhs[4], "cuVec");

    if (mxGetNumberOfElements(prhs[5]) && mxGetClassID(prhs[5]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument incCuVec has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[5]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Argument incCuVec should be a scalar.");
    incCuVec = *(int32_T*)mxGetData(prhs[5]);

    if (mxGetNumberOfElements(prhs[6]) && mxGetClassID(prhs[6]) != mxSTRUCT_CLASS)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongInputType",
            "Input argument strm has incorrect data type; struct is expected.");
    if (mxGetNumberOfElements(prhs[6]) != 1)
        mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:WrongSizeOfInputArg",
            "Argument strm should be a scalar.");
    marshallin_const_struct1_T(&strm, prhs[6], "strm");

    errCode = mxMalloc(sizeof(int32_T));

    toplevel = mxMalloc(sizeof(boolean_T));

    /* Invoke the target function */
    cuVecCopySubToGPU_async(n, &vec, istart, inc, &cuVec, incCuVec, &strm, errCode, toplevel);

    /* Deallocate input and marshall out function outputs */
    /* Nothing to be done for n */
    free_emxArray((emxArray__common*)(&vec));
    /* Nothing to be done for istart */
    /* Nothing to be done for inc */
    /* Nothing to be done for incCuVec */
    destroy_struct1_T(&strm);
    plhs[0] = move_scalar_to_mxArray(errCode, mxINT32_CLASS);
    plhs[1] = move_scalar_to_mxArray(toplevel, mxLOGICAL_CLASS);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    /* Temporary copy for mex outputs. */
    mxArray *outputs[2];
    int i;
    int nOutputs = (nlhs < 1 ? 1 : nlhs);

    if (nrhs == 6) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cuVecCopySubToGPU:TooManyOutputArguments",
                "Too many output arguments for entry-point cuVecCopySubToGPU.\n");
        /* Call the API function. */
        __cuVecCopySubToGPU_api(outputs, prhs);
    }
    else if (nrhs == 7) {
        if (nlhs > 2)
            mexErrMsgIdAndTxt("cuVecCopySubToGPU_async:TooManyOutputArguments",
                "Too many output arguments for entry-point cuVecCopySubToGPU_async.\n");
        /* Call the API function. */
        __cuVecCopySubToGPU_async_api(outputs, prhs);
    }
    else
        mexErrMsgIdAndTxt("cuVecCopySubToGPU:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point cuVecCopySubToGPU.");

    /* Copy over outputs to the caller. */
    for (i = 0; i < nOutputs; ++i) {
        plhs[i] = outputs[i];
    }
}
