/*
 * crs/codegen/lib/crs_rowind/crs_rowind_mex.c
 *
 * Auxiliary code for mexFunction of crs_rowind
 *
 * C source code generated by m2c.
 * %#m2c options:3a3a78c1ad8855a34e1da525327f6cab
 *
 */

#include "mex.h"
#if !defined(MATLAB_MEX_FILE) && defined(printf)
#undef printf
#endif
/* Include the C header file generated by codegen in lib mode */
#include "crs_rowind.h"
#include "m2c.c"

/* Include declaration of some helper functions. */
#include "lib2mex_helper.c"


static void __crs_rowind_api(mxArray **plhs, const mxArray ** prhs) {
    emxArray_int32_T     rowptr;
    emxArray_int32_T     js;
    emxArray_int32_T     is;

    /* Marshall in inputs and preallocate outputs */
    if (mxGetNumberOfElements(prhs[0]) && mxGetClassID(prhs[0]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_rowind:WrongInputType",
            "Input argument rowptr has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[0]) && mxGetDimensions(prhs[0])[1] != 1) 
        mexErrMsgIdAndTxt("crs_rowind:WrongSizeOfInputArg",
            "Dimension 2 of rowptr should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[0], (emxArray__common *)(&rowptr), "rowptr", 1);

    if (mxGetNumberOfElements(prhs[1]) && mxGetClassID(prhs[1]) != mxINT32_CLASS)
        mexErrMsgIdAndTxt("crs_rowind:WrongInputType",
            "Input argument js has incorrect data type; int32 is expected.");
    if (mxGetNumberOfElements(prhs[1]) && mxGetDimensions(prhs[1])[1] != 1) 
        mexErrMsgIdAndTxt("crs_rowind:WrongSizeOfInputArg",
            "Dimension 2 of js should be equal to 1.");
    alias_mxArray_to_emxArray(prhs[1], (emxArray__common *)(&js), "js", 1);
    init_emxArray((emxArray__common*)(&is), 1);

    /* Invoke the target function */
    crs_rowind(&rowptr, &js, &is);

    /* Deallocate input and marshall out function outputs */
    free_emxArray((emxArray__common*)(&rowptr));
    free_emxArray((emxArray__common*)(&js));
    plhs[0] = move_emxArray_to_mxArray((emxArray__common*)(&is), mxINT32_CLASS);
    mxFree(is.size);

}


void mexFunction(int nlhs, mxArray *plhs[], int nrhs, const mxArray *prhs[]) {
    if (nrhs == 2) {
        if (nlhs > 1)
            mexErrMsgIdAndTxt("crs_rowind:TooManyOutputArguments",
                "Too many output arguments for entry-point crs_rowind.\n");
        /* Call the API function. */
        __crs_rowind_api(plhs, prhs);
    }
    else
        mexErrMsgIdAndTxt("crs_rowind:WrongNumberOfInputs",
            "Incorrect number of input variables for entry-point crs_rowind.");
}
