/*
 * This file contains some helper functions used by the main function
 * generated by lib2exe.
 */

#include <string.h>
#include <stdio.h>
#include "mat.h"

/* Error message */
void m2cErrMsgIdAndTxt(const char *id, const char *msg) {
    fprintf(stderr, "%s - %s\n", id, msg);
    abort();
}

/* Read input file. Returns 0 if successful. */
int readInputArgs(const char *filename, const int nrhs, mxArray *prhs[]) {
    int  i;
    const char *varname;
    
    MATFile *pmat = matOpen(filename, "r");
    
    if (!pmat) {
        fprintf(stderr, "Error in opening input file %s\n", filename);
        return(-1);
    }
    
    for (i=0; i<nrhs; ++i) {
        prhs[i] = matGetNextVariable(pmat, &varname);
        
        if (!prhs[i]) {
            fprintf(stderr, "There are only %d variables in input file %s. %d expected.\n", i, filename, nrhs);
            return(-1);
        }
    }
    
    /* Read in remaining varilables in the file */
    while (matGetNextVariable(pmat, &varname)) {
        fprintf(stderr, "Warning: Ignoring extra varilable %s in file %s\n",
                varname, filename);
    }
    
    if (matClose(pmat)) {
        fprintf(stderr, "Error closing file %s\n", filename);
        return(-1);
    }
    
    return 0;
}

/* Write output MAT file. Returns 0 if successful. */
int writeOuputArgs(const char *filename, const int nOut, mxArray *plhs[]) {
    int  i;
    char varname[65];
    
    MATFile *pmat = matOpen(filename, "w");
    
    if (!pmat) {
        fprintf(stderr, "Error in opening output file %s\n", filename);
        return(-1);
    }
    
    for (i=0; i<nOut; ++i) {
        if (!plhs[i]) 
            break;
        
        sprintf(varname, "output_%d", i+1);
        if (matPutVariable(pmat, varname, plhs[i])) {
            fprintf(stderr, "Error in when writing output %d into file %s\n", i, filename);
            abort();
        }
    }
    
    if (matClose(pmat)) {
        fprintf(stderr, "Error closing file %s\n", filename);
        return(-1);
    }
    
    return 0;
}